### ISSUE TITLE
Failed to load checkpoints

### ISSUE THREAD

**Issue by reeyon** [TheDevMinerTV/Checkpoint-Generator#1]
![image](https://user-images.githubusercontent.com/3666089/59020481-acec4b80-887c-11e9-9b69-505caf3ca4bd.png)

the saved checkpoints.csv is the correct format, but the any daemon will just pop up this error upon launched.

**Comment by TheDevMinerTV** [comment]
Already known, please see the README

**Comment by TheDevMinerTV** [comment]
Should be fixed now :)
Closing...
