### ISSUE TITLE
TypeError: daemon.getBlockCount is not a function

### ISSUE THREAD

**Issue by dagwood-Fenichuck** [TheDevMinerTV/Checkpoint-Generator#17]
Hi Guys was there a fix for this I changed
 
daemon.blockCount().then(async (height) => {
	console.log("Got blockheight " + height + "!");

daemon.getblockCount().then(async (height) => {
	console.log("Got blockheight " + height + "!");

  but can't get it to generate the current checkpoints.csv   any help would be appreciated 

> checkpoint_generator@1.0.0 start /home/seed4/Checkpoint-Generator
> node checkpoint_generator.js

/home/seed4/Checkpoint-Generator/checkpoint_generator.js:20
daemon.getblockCount().then(async (height) => {
       ^

TypeError: daemon.getblockCount is not a function
    at Object.<anonymous> (/home/seed4/Checkpoint-Generator/checkpoint_generator.js:20:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! checkpoint_generator@1.0.0 start: `node checkpoint_generator.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the checkpoint_generator@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/seed4/.npm/_logs/2021-01-11T12_55_48_688Z-debug.log

**Comment by TheDevMinerTV** [comment]
All you should have to do is:
```sh
npm i
node .
```

Tell me how it went.

**Comment by dagwood-Fenichuck** [comment]
Hi thanks for the reply i have done npm i and node .   i get this error 
seed3@vmi419579:~/Checkpoint-Generator$ node .
/home/seed3/Checkpoint-Generator/checkpoint_generator.js:20
daemon.blockcount().then(async (height) => {
       ^

TypeError: daemon.blockcount is not a function
    at Object.<anonymous> (/home/seed3/Checkpoint-Generator/checkpoint_generator.js:20:8)
 This is the full file

const fs = require('fs'),
      { TurtleCoind } = require('turtlecoin-rpc');

const daemon = new TurtleCoind({
	host: '207.180.194.21', // ip address or hostname of the host
	port: 20101, // what port is the RPC server running on
	timeout: 30000, // request timeout
	ssl: false // whether we need to connect using SSL/TLS 
});

class Checkpoint {
	constructor(height, hash) {
		this.height = height;
		this.hash = hash;
	}
}

var checkpoints = [];

daemon.blockcount().then(async (height) => {
	console.log("Got blockheight " + height + "!");

	for (let i = 1; i < height; i++) {
		console.log("Getting block info for height " + i);

		const blockHash = await daemon.blockHeaderByHeight(i)

		checkpoints.push(new Checkpoint(i - 1, blockHash));
	}

	console.log('Got', checkpoints.length, 'checkpoints from 0 to', checkpoints[checkpoints.length - 1].height, 'blocks');

	let csv = ''

	for (const checkpoint of checkpoints) {
		csv += `${checkpoint.height},${checkpoint.hash}\n`
	}

	const buffer = Buffer.from(csv, 'ascii');

	fs.open('checkpoints.csv', 'w', (err, fd) => {
		if (err) throw err

		console.log('Opened checkpoints.csv!');

		fs.write(fd, buffer, 0, buffer.byteLength, 0, (err, bytes) => {
			if(err) throw err;

			console.log('Wrote', Math.floor(bytes / 1024), ' kilobytes');

			fs.close(fd, (err) => {
				console.log('Closed checkpoints.csv!');
			});
		});
	})
})
.catch((error) => {
	throw new Error(`An error occurred whilst getting height of the blockchain : ${error}`);
});

**Comment by TheDevMinerTV** [comment]
Please use the original code, you've clearly used tampered code.
```
git reset --hard
```

**Comment by dagwood-Fenichuck** [comment]
hi have reinstalled it  from github  in /home/seed3  cd into Checkpoint-Generator npm i  then node . returns this error again
daemon.blockCount().then(async (height) => {
       ^

TypeError: daemon.blockCount is not a function
    at Object.<anonymous> (/home/seed3/Checkpoint-Generator/checkpoint_generator.js:20:8)

This the file from that git download=> is this the correct code

const daemon = new TurtleCoind({
	host: '127.0.0.1', // ip address or hostname of the Telluriumd host
	port:  20101, // what port is the RPC server running on
	timeout: 30000, // request timeout
	ssl: false // whether we need to connect using SSL/TLS
});

class Checkpoint {
	constructor(height, hash) {
		this.height = height;
		this.hash = hash;
	}
}

var checkpoints = [];

daemon.blockCount().then(async (height) => {
	console.log("Got blockheight " + height + "!");

	for (let i = 1; i < height; i++) {
		console.log("Getting block info for height " + i);

		const blockHash = await daemon.blockHeaderByHeight(i)

		checkpoints.push(new Checkpoint(i - 1, blockHash));
	}

	console.log('Got', checkpoints.length, 'checkpoints from 0 to', checkpoints[checkpoints.length - 1].height, 'blocks');

	let csv = ''

	for (const checkpoint of checkpoints) {
		csv += `${checkpoint.height},${checkpoint.hash}\n`
	}

	const buffer = Buffer.from(csv, 'ascii');

	fs.open('checkpoints.csv', 'w', (err, fd) => {
		if (err) throw err

		console.log('Opened checkpoints.csv!');

		fs.write(fd, buffer, 0, buffer.byteLength, 0, (err, bytes) => {
			if(err) throw err;

			console.log('Wrote', Math.floor(bytes / 1024), ' kilobytes');

			fs.close(fd, (err) => {
				console.log('Closed checkpoints.csv!');
			});
		});
	})
})
.catch((error) => {
	throw new Error(`An error occurred whilst getting height of the blockchain : ${error}`);
});

**Comment by TheDevMinerTV** [comment]
Did any errors occur whilst the modules were installing?

**Comment by dagwood-Fenichuck** [comment]
Yes i module as below,  but i ran npm i  again and all seemed to install okay

Error: Cannot find module 'turtlecoin-rpc'
Require stack:
- /home/seed3/Checkpoint-Generator/checkpoint_generator.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/seed3/Checkpoint-Generator/checkpoint_generator.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/seed3/Checkpoint-Generator/checkpoint_generator.js' ]
}

**Comment by TheDevMinerTV** [comment]
Could you re-download the repository again?
I think I've fixed the issue :)

```sh
git reset --hard && git pull
```

**Comment by dagwood-Fenichuck** [comment]
Yes did that now produced a small
SyntaxError: Unexpected token ')'

seed3@vmi419579:~/Checkpoint-Generator$ node .
/home/seed3/Checkpoint-Generator/checkpoint_generator.js:33
        const csv = checkpoints.map((c) => `${checkpoint.height},${checkpoint.hash}`).join('\n'));

**Comment by TheDevMinerTV** [comment]
Fixed

**Comment by dagwood-Fenichuck** [comment]
i did git reset --hard && git pull  again  i get this

seed3@vmi419579:~/Checkpoint-Generator$ node .
(node:17679) UnhandledPromiseRejectionWarning: Error: An error occurred whilst getting height of the blockchain : StatusCodeError: 404 - undefined
    at /home/seed3/Checkpoint-Generator/checkpoint_generator.js:38:8
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17679) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17679) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dagwood-Fenichuck** [comment]
`node --trace-warnings ...`
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/home/seed3/Checkpoint-Generator/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by TheDevMinerTV** [comment]
When was your coin forked from Turtlecoin? Was it after Turtlecoin version v0.20.0?

**Comment by dagwood-Fenichuck** [comment]
Yes sir it was it is the current release

**Comment by TheDevMinerTV** [comment]
Then you have to modify the code to use turtlecoin-rpc v3. That version of the library uses other calls though. Please look into it yourself

**Comment by dagwood-Fenichuck** [comment]
ah Okay  thank you for the time and help you spent with me regards dagwood
